# -*- coding: utf-8 -*-
"""Breast_cancer_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f7is0_RBoErImLH7U3ZW3Rv4eq2LMg6s
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import missingno as msno
import io

import warnings
warnings.filterwarnings('ignore')

sns.set()
plt.style.use('ggplot')

df = pd.read_csv('/content/breast-cancer.csv')

df.head()

df.tail()

df['diagnosis'].value_counts()

"""Data preprocessing

"""

df.diagnosis.unique()

# M -> Malignant
# B -> Benign
df.describe()

df.info()

# missing value
# df.isna().sum()
df.isnull().sum()

msno.bar(df, color='blue')

"""There is no missing value"""

# df['diagnosis'] = df['diagnosis'].apply(lambda val:1 if val=='M' else 0)
df.replace({"diagnosis": {"M": 1, "B": 0}}, inplace=True)

plt.hist(df['diagnosis'])
plt.title('diagnosis(M=1, B=0)')
plt.show()

"""EDA"""

# each 5 row has 6 columns
# density graph
plt.figure(figsize=(20,15))
plotnumber = 1
for column in df:
  if plotnumber <= 30:
    ax = plt.subplot(5,6,plotnumber)
    sns.distplot(df[column])
    plt.xlabel(column)
  plotnumber += 1

plt.tight_layout()
plt.show()

df.corr()

# heatmap
plt.figure(figsize=(20,12))
corr = df.corr()
mask = np.triu(np.ones_like(corr, dtype= bool))
sns.heatmap(corr, mask = mask, linewidths = 1, annot = True, fmt = ".2f")
plt.show()

# highly correlated
# multicollinearity

df.drop('id', axis=1, inplace = True)

# feature selection column
corr_matrix = df.corr().abs()
mask = np.triu(np.ones_like(corr_matrix, dtype= bool))
tri_df = corr_matrix.mask(mask)

to_drop = [x for x in tri_df.columns if any(tri_df[x] > 0.92)]

df = df.drop(to_drop, axis = 1)
print(df.shape[1])

df.head()

"""32 features are reduced to 23 now"""

# ml model
X = df.drop('diagnosis', axis = 1)
y = df['diagnosis']

# spliting data into training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

# scaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train.shape

X_test.shape

# applying ml algo
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

y_pred = log_reg.predict(X_test)

y_pred

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(accuracy_score(y_train, log_reg.predict(X_train)))
log_reg_acc = accuracy_score(y_test, log_reg.predict(X_test))
print(log_reg_acc)
# confusion matrices
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""Logistic regression accuracy is 96% on testing data and 98% accuracy in training"""

# Decision tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
dtc = DecisionTreeClassifier()
parameter ={
    'criterion' :['gini', 'entropy'],
    'max_depth' : range(2,32,1),
    'min_samples_split' : range(2,10,1),
    'min_samples_leaf' : range(1,10,1),
    'splitter' : ['best', 'random']
}

grid_search_dt = GridSearchCV(dtc,parameter, cv = 5, n_jobs = -1, verbose =1)
grid_search_dt.fit(X_train, y_train)

grid_search_dt.best_params_

grid_search_dt.best_score_

dtc = DecisionTreeClassifier(criterion = 'entropy', max_depth=15, min_samples_leaf = 4, min_samples_split = 5, splitter ='random')
dtc.fit(X_train, y_train)

print(accuracy_score(y_train, dtc.predict(X_train)))
dtc_acc = accuracy_score(y_test, dtc.predict(X_test))
print(dtc_acc)
y_pred = dtc.predict(X_test)
# confusion matrices
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""decision tree there is 96% accuracy on testing data and 91% on training data"""

models = pd.DataFrame({
    'Model': ['Logistic Regression', 'Decision Tree'],
    'Score': [100*round(log_reg_acc,4), 100*round(dtc_acc,4)]
})
models.sort_values(by = 'Score', ascending = False)